import { Inter } from "next/font/google";
import Sidebar from "./app/components/Sidebar";
import Header from "./app/components/Header";

import "@/app/globals.css";

const font = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <div className="justify-between bg-white">
          <Sidebar />
        </div>
        <main className="ml-20 min-h-screen">
          <Header />
          {children}
        </main>
      </body>
    </html>
  );
}

// TODO: Add favicons generation to Tholattice dashboard,home, and sites route
