import { Inter } from "next/font/google";
import "@/app/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-red-800">
          {children}This is the tholattice home layout
        </div>
      </body>
    </html>
  );
}

// export const metadata = {
//   title: "Next.js",
//   description: "Generated by Next.js",
// };

// export default function RootLayout({
//   children,
// }: // params,
// {
//   children: React.ReactNode;
//   // params: { site: string };
// }) {
//   // console.log(params.site);
//   return (
//     <html lang="en">
//       <body>{children}</body>
//     </html>
//   );
// }

// import "./globals.css";
